import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from "react";

import Link from 'next/link'

export default function Home() {

  // Query API - Used For Backend Tasks
  const axios = require('axios');
  axios.defaults.headers.common['Authorization'] = 'Bearer 2:Gwxyp4p98c8ek50z8WUGXSZdpnCjUd9VWjR6l3fqV3huIaewQ4cg';
  axios.get('https://api.optimizely.com/v2/experiments?project_id=20759430581')
  .then(function (response) {
    console.log('Experiment Data Example', response);
  
  })
  .catch(function (error) {
    console.log(error);
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Optimizely Rest API Example
        </h1>

        <div> 
          <Link href="/i">
            <a>Homepage</a>
          </Link>
        </div>
        
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
