import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import React, { useEffect, useState } from "react";
import Cookies from 'js-cookie';
import Link from 'next/link'

export default function Home() {

  const [componentIfBucketed, renderComponentIfUserIsBucketed] = useState(null);

  useEffect(() => {

    const optimizelyData = window?.optimizely?.get('data');
    console.log("Optimizely Data", optimizelyData);

    const visitorData = window?.optimizely?.get('visitor');
    console.log("Visitor Data", visitorData);  // Can get by user id here

    const stateData = window?.optimizely?.get('state');
    console.log("State Data", stateData);

    const userIdByCookie = Cookies?.get('optimizelyEndUserId');
    console.log("UserIdByCookie", userIdByCookie);

    const experiments = stateData?.getExperimentStates({
      "isActive": true 
    });
    console.log("Experiment Data", experiments);
    console.log("Variation Data", experiments?.variation);

    const experimentId = '21118060750';
    const variationOneId = '21122810749';

    if (experiments[experimentId]?.variation?.id === variationOneId) {
      renderComponentIfUserIsBucketed(<div>This component is added in code only when the user is bucketed using the API!</div>);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      {/* Call Opti-Web and set beforeInteractive */}
      <Script src="https://cdn.optimizely.com/js/20759430581.js" type="text/javascript" strategy="beforeInteractive" />
      
      <main className={styles.main}>

        <h1 className={styles.title}>
          Optimizely Web API Example
        </h1>

        <div>
          {componentIfBucketed || null}
        </div>

        <div> 
          <Link href="/api">
            <a>Optimizely Rest API Example</a>
          </Link>
        </div>
        
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
