import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import * as React from "react";
import Cookies from 'js-cookie';

export default function Home() {

  // Query API - Used For Backend Tasks
  const axios = require('axios');
  axios.defaults.headers.common['Authorization'] = 'Bearer 2:Gwxyp4p98c8ek50z8WUGXSZdpnCjUd9VWjR6l3fqV3huIaewQ4cg';
  axios.get('https://api.optimizely.com/v2/experiments?project_id=20759430581')
  .then(function (response) {
    console.log('Experiment Data Example', response);
  
  })
  .catch(function (error) {
    console.log(error);
  });

  React.useEffect(() => {
    const optimizelyData = window.optimizely.get('data');
    const visitorData = window.optimizely.get('visitor');
    const stateData = window.optimizely.get('state');

    const experiment = optimizelyData.experiments['21046670341'];
    const userIdByCookie = Cookies.get('optimizelyEndUserId')

    const experiments = stateData.getExperimentStates({
      "isActive": true
    });

    console.log("Optimizely Data", optimizelyData);
    console.log("Experiment Data", experiment);
    console.log("Visitor Data", visitorData);  // Can get by user id here
    console.log("State Data", stateData);
    console.log("UserIdByCookie", userIdByCookie);
    console.log("Experiments", experiments);

  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Script src="https://cdn.optimizely.com/js/20759430581.js" type="text/javascript" />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Optimizely Web API Example
        </h1>

        <div>Experiment One</div>

        <div>Experiment Two</div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
